---
title: "Arms Trade Data Prep"
author: "Simon & Fabio"
date: "5 1 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages

```{r}
pacman::p_load(dplyr, haven, stringr, ggplot2, streamgraph, ggthemr, ggrepel)
```


# Load and Prep Data

## V-Dem Data

```{r}
load(url("https://github.com/favstats/database_delib/raw/master/vdems_start.Rdata"))

vdem <- vdems_start %>%
  select(
    country_name, 
    country_text_id, year, 
    v2clkill, e_regionpol
  ) %>%
  rename(
    cname = country_name, 
    iso3 = country_text_id,
    pkill = v2clkill,
    pregion = e_regionpol
  )

#save(vdem, file = "data/vdem_sub.Rdata")
```

## Armstrades

```{r, eval = F}
library(RCurl)
url <- "http://armstrade.sipri.org/armstrade/html/export_trade_register.php"
armstrades <- postForm(
  url,
  low_year = "1950",
  high_year = "2016",
  seller_country_code = "USA NATO RUS USR CHI",
  buyer_country_code = "",
  armament_category_id = "any",
  buyers_or_sellers = "sellers",
  filetype = "csv",
  include_open_deals = "on",
  sum_deliveries = "on",
  Submit4 = "Download"
  ) %>%
  readr::read_csv()

save(armstrades, file = "data/armstrades.Rdata")
```

```{r}
load("data/armstrades.Rdata")
```

## Defining Actors

```{r}
nonstates <- c("African Union**", "ANC (South Africa)*",
  "Anti-Castro rebels (Cuba)*", "Armas (Guatemala)*", 
  "Contras (Nicaragua)*", "FNLA (Angola)*", "Haiti rebels*",
  "Indonesia rebels*", "Khmer Rouge (Cambodia)*", "Mujahedin (Afghanistan)*", 
  "NATO**", "Northern Alliance (Afghanistan)*", "Pathet Lao (Laos)*", 
  "PLO (Israel)*", "Regional Security System**", "Ukraine Rebels*",
  "UNITA (Angola)*", "United Nations**", "Unknown recipient(s)",
  "Viet Cong (South Vietnam)*", "Viet Minh (France)*", "ZAPU (Zimbabwe)*")

nonstates %>% head
```

```{r}
states <- c("Australia", "Austria", "Belgium", "Canada", "Switzerland", "Cyprus", "Germany", "Denmark", "Spain", "Finland", "France", "United Kingdom of Great Britain and Northern Ireland", "Greece", "Ireland", "Iceland", "Italy", "Netherlands", "Norway", "New Zealand", "Portugal", "Sweden",  "United States", "United Kingdom", "Russia") %>% 
  countrycode::countrycode(., "country.name", "iso3c")
#states_norm <- states_norm[-length(states_norm)]
```

Clean and preocess Arms Trade data

```{r}
# prep armstrades for merging
library(countrycode)

arms1 <- armstrades %>%
  filter(!(buyer %in% nonstates)) %>%
  mutate(iso3 = countrycode(buyer, "country.name", "iso3c")) %>%
  select(ldat, tivdel, iso3, alliance) %>%
  rename(year = ldat, tiv = tivdel) %>%
  mutate(year = as.character(year)) %>%
  #filter(year != 0) %>%
  group_by(alliance, iso3, year) %>%
  summarise(sumtiv = sum(tiv, rm.na = T)) %>%
  ungroup()# %>%
  # filter(!is.na(buyer)) %>%
  # tidyr::spread(alliance, mtiv) %>%
  # mutate(buyer = countrycode::countrycode(buyer, origin = "country.name", destination = "country.name")) %>%
  # rename(cname = buyer) %>%
  # mutate(year = as.character(year))
```

merging with vdem 

```{r}
# prep vdem for merging
arm1_vdm <- vdem %>%
  filter(year >= 1950) %>%
  mutate(year = as.character(year)) %>%
  #mutate(cname = countrycode::countrycode(cname, origin = "country.name", destination = "country.name")) %>%
  left_join(arms1, by = c("iso3", "year"))
```

create influence variable (first percentages).

```{r}
arms_year <- arm1_vdm %>% 
  filter(year >= 1950) %>%
  select(cname, iso3, year, sumtiv, alliance) %>%
  group_by(alliance, cname, iso3, year) %>%
  summarise(
    sumtiv = sum(sumtiv, rm.ma = T)
  ) %>%
  mutate(sumtiv = ifelse(is.na(sumtiv), 0, sumtiv)) %>%
  ungroup() %>%
  group_by(alliance, year) %>%
  mutate(perc = round(sumtiv / sum(sumtiv), 4)) %>%
  mutate(perc_label = paste0(perc*100, " %")) %>% 
  ungroup()
```

creepy base function

```{r}
arms_year$perc[arms_year$alliance %in% "Russia"] <- arms_year$perc[arms_year$alliance %in% "Russia"]*-1
```


```{r}
library(tidyr)
arms_cname <- arms_year %>%
  select(alliance, cname, iso3, perc) %>%
  group_by(cname, iso3) %>%
  summarise(mperc = mean(perc, na.rm = T)) %>%
  ungroup() %>%
  mutate(cname = case_when(
    grepl("Republic of Korea", cname) ~ "North Korea",
    grepl("German Democratic", cname) ~ "East Germany",
    cname == "Iran (Islamic Republic of)" ~ "Iran",
    cname == "Lao People's Democratic Republic" ~ "Laos",
    cname == "Republic of Korea" ~ "South Korea",
    cname == "Syrian Arab Republic" ~ "Syria",
    cname == "Taiwan, Province of China" ~ "Taiwan",
    cname == "Venezuela, Bolivarian Republic of" ~ "Venezuela",
    cname == "Yemen People's Republic" ~ "Yemen (Socialist)",
    TRUE ~ cname)
  ) #%>% 
  # mutate(
  #   affil = case_when(
  #     affil == "Russian" ~ "(Soviet) Russia",
  #     affil == "Western" ~ "Western Countries"
  #   )
  # )
#+arms_year$sumperc <- rowSums(arms_year[, c("perc_r", "perc_w")])

save(arms_cname, file = "data/arms_cname.Rdata")
save(arm1_vdm, file = "data/arm1_vdm.Rdata")
save(arms_year, file = "data/arms_year.Rdata")
```

```{r, eval = F}
range01 <- function(x){(x - min(x, na.rm = T)) / (max(x, na.rm = T) - min(x, na.rm = T))}

nn3 <- nn21 %>%
  mutate(affil = case_when(
#    perc_r > perc_w ~ "Russian",
#    perc_w > perc_r ~ "Western",
    perc_r > 0.05 & perc_w < 0.01 ~ "Russian",
    perc_w > 0.05 & perc_r < 0.01 ~ "Western",
    TRUE ~ NA_character_
    )
  ) %>%
  ungroup() %>%
  left_join(nn2 %>% select(cname, year, pkill)) %>%
  filter(!is.na(affil)) %>%
  mutate(perc_all = ifelse(affil == "Russian", perc_r, perc_w), year = as.numeric(year)) %>%
  mutate(pkill = 4 - (range01(pkill) * 4))
```

```{r}
series = list(
  list(
    name = 'Hola linea',
    color = 'red',
    data = c(29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4)
  )
)


series = list(
  list(
    name = 'Hola linea',
    color = 'red',
    data = c(29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4)
  ),
  list(
    name = 'Reverse!',
    color = 'green',
    data = c(54.4, 95.6, 194.1, 216.4, 148.5, 135.6, 176, 144, 129.2, 106.4, 71.5, 29.9)
  )
)



library(highcharter)
library(tidyverse)

gg1 <- highchart() %>%
  hc_add_series_list(series)

gg1$x$hc_opts$series
gg1
```

## Highcharter train space

* [best highcahrts tutorial](https://dantonnoriega.github.io/ultinomics.org/post/2017-04-05-highcharter-explainer.html)


